### PR TITLE
ci: fix and improve completeness of nightly scans

### LINKED ISSUE #527: run nightly scans on actual released connaisseur image
**Describe the feature**
currently, the trivy vulnerability scan runs on a freshly build image, but should at least in addition run on the actual remote image.

### PR DESCRIPTION
**Pull request by xopham**
fixes #527

## Description

* make sure nightly scans work and provide a full picture
* example see here: https://github.com/sse-secure-systems/connaisseur/runs/5424795881?check_suite_focus=true

## Checklist

- [x] PR is rebased to/aimed at branch `develop`
- [x] PR follows [Contributing Guide](https://github.com/sse-secure-systems/connaisseur/blob/master/docs/CONTRIBUTING.md)
- [x] Added tests (if necessary)
- [x] Extended README/Documentation (if necessary)
- [x] Adjusted versions of image and Helm chart in `values.yaml` and `Chart.yaml` (if necessary)

### CODE REVIEW

File: tests/integration/integration-test.sh [hunk 1]
```diff
@@ -153,6 +165,17 @@ helm_upgrade() {
   echo -e "${SUCCESS}"
 }
 
+helm-repo_upgrade() {
```
Comment (Starkteetje) [inline tests/integration/integration-test.sh:168]: This doesn't seem to be called anywhere

Comment (xopham) [reply tests/integration/integration-test.sh:168]: yes, extended here for completeness as otherwise there is no way to use the artifact repo with custom values.yaml and I felt I may just directly increase functionality here. Should I remove?

Comment (xopham) [reply tests/integration/integration-test.sh:168]: the way the above helm-repo_install works is deploying the artifacthub charts as is. this part allows later upgrade to a specific `values.yaml` to allow testing with non-default settings. I consider this useful, but have not implemented a test yet

Comment (Starkteetje) [reply tests/integration/integration-test.sh:168]: You consider it useful as in you do use it locally? In that case, I'd see the value but would ask that you explain the use case in a comment

Comment (xopham) [reply tests/integration/integration-test.sh:168]: see below in line 170. will move 1 line up

Comment (Starkteetje) [reply tests/integration/integration-test.sh:168]: I think for the shell code, we did comments ahead of their definition.

Would add context to the comment:
When testing locally and you installed Conaisseur via helm-repo_install (why -_ btw?), you can call this function in an adapted or added test (because you cant call this from outside this file, right?) to set ...

Comment (xopham) [reply tests/integration/integration-test.sh:168]: ok, will remove

**Review by Starkteetje — APPROVED** [review]
