### PR TITLE
fix: added subjectAltNames to TLS certificates

### LINKED ISSUE #4: TLS Certificates Fix
The TLS certificates for connaisseur have subjectAltNames defined for them in the CSR config file, but they stll don't appear in the resulting certificates. This is caused by a known OpenSSL [bug](https://www.openssl.org/docs/man1.1.0/man1/x509.html#BUGS). These subjectAltNames are mandatory in Kubernetes v1.19 and need to be added or connaisseur will break.

### PR DESCRIPTION
**Pull request by phbelitz**
Kubernetes v1.19 requires subjectAltNames to be present on the TLS certificates or otherwise will break. Even though the TLS config file already added those, an OpenSSL bug prevented them to be actually propagated to the actual certificates.

closes #4

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -17,4 +17,4 @@ testing-env/aks/k8s/deployment.yaml
 samples/*
 demo/
 ca.conf
```
Comment (peterthomassen) [inline .gitignore:19]: is this line still needed?

File: helm/certs/gen_certs.sh [hunk 2]
```diff
@@ -47,5 +38,6 @@ DNS.2 = $SERVICE_NAME-svc.$SERVICE_NAME
 DNS.3 = $SERVICE_NAME-svc.$SERVICE_NAME.svc
 DNS.4 = $SERVICE_NAME-svc.$SERVICE_NAME.svc.cluster.local
 EOF
-openssl req -new -key tls-key.pem -subj "/CN=$SERVICE_NAME-svc.$SERVICE_NAME.svc" -out tls.csr -config tls.conf
-openssl x509 -req -in tls.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out tls-crt.pem
+
+openssl req -new -key tls.key -sha256 -config tls-csr.conf -subj "/CN=$SERVICE_NAME-svc.$SERVICE_NAME.svc" -out tls.csr
+openssl x509 -req -days 365 -in tls.csr -signkey tls.key -sha256 -extensions v3_ca -extfile tls-crt.conf -out tls.crt
```
Comment (peterthomassen) [inline helm/certs/gen_certs.sh:43]: Is 365 days enough / is there a rotation mechanism?

Comment (peterthomassen) [reply helm/certs/gen_certs.sh:43]: Also, are we signing with the same key that the certificate is for? Please check with @Starkteetje if that's ok

**Review by peterthomassen — APPROVED** [review]
lgtm, modulo validity period and @Starkteetje's feedback on the signing key setting

File: helm/certs/gen_certs.sh (hunk 2 above)
Comment (Starkteetje) [reply helm/certs/gen_certs.sh:43]: It's supposed to be a self-signed cert, right? In that case that's fine

**Review by peterthomassen — APPROVED** [review]
lgtm, although Connaisseur will break unexpectedly after 10 years. Why not set it to 100 years?

Also, one conversation is still open, but it's not so important.

**Comment by peterthomassen** [comment]
oh, and next time please add a fixup commit (`git commit --fixup=...`) so that can review the changes more easily, and then squash after approval.

**Review by peterthomassen — APPROVED** [review]
