### PR TITLE
fix: support api versions for k8s workloadobjects, add tests

### LINKED ISSUE #382: Update supported k8s resources and api version
**Describe the bug**
with latest releases API versions and available resources have changed. Connaisseur should support the latest changes.

### PR DESCRIPTION
**Pull request by xopham**
fixes #382 

## description
- adds integration tests for workload objects and api versions for each Kubernetes version
- fixes currently unsupported api versions

## checklist
- [x] according to Contributing guide
- [x] tests added where necessary

### CODE REVIEW

**Comment by annekebr** [comment]
This PR is not only related to `tests` as it changes the supported API versions of Connaisseur as well, which should be a separate PR I think

**Comment by xopham** [comment]
@annekebr but then this pr fails. I renamed the pr to make it: fixing the workload object api versions, added tests accordingly. Would that work?

File: tests/integration/workload-objects-integration-test.sh [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+    # UNSIGNED
+    export TAG=unsigned
+
+    echo -e "\n** Render '${KIND}' using '${APIVERSION}' and '${TAG}' image"
+    envsubst < tests/integration/workload-objects/${KIND}.yaml | cat
+
+    echo -e "\n** Deploy '${KIND}' using '${APIVERSION}' and '${TAG}' image"
+    envsubst < tests/integration/workload-objects/${KIND}.yaml | kubectl apply -f - >output.log 2>&1 || true
+
+    if [[ ! "$(cat output.log)" =~ 'Unable to find signed digest for image docker.io/securesystemsengineering/testimage:unsigned.' ]]; then
```
Comment (annekebr) [inline tests/integration/workload-objects-integration-test.sh:33]: It would probably be sufficient to deploy a valid signed image without error, wouldn't it? But as long as we don't run into timing issues, I don't mind testing more :)

**Review by annekebr — DISMISSED** [review]

File: tests/integration/workload-objects-integration-test.sh (hunk 1 above)
Comment (xopham) [reply tests/integration/workload-objects-integration-test.sh:33]: that is what I thought and it seems that the k3s never fails with timing issues

**Review by annekebr — APPROVED** [review]
